---
- name: Add AWX Credentials
  awx.awx.credential:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    organization: "{{ item.organization | default('gepaplexx') }}"
    credential_type: "{{ item.credential_type }}"
    inputs: "{{ item.inputs | default({}) }}"
    # update_secrets default set to false for development
    update_secrets: "{{ item.update_secrets | default(true) }}"
    state: present
    validate_certs: true
    controller_host: "{{ awx_iac_host_ip }}"
    controller_username: "{{ awx_iac_user }}"
    controller_password: "{{ awx_iac_pass }}"
  loop: "{{ awx_iac_credentials }}"
  no_log: true
