---
- name: Add AWX Organisation
  awx.awx.organisation:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    state: present
    validate_certs: false
    controller_host: "{{ awx_host_ip }}"
    controller_username: "{{ awx_user }}"
    controller_password: "{{ awx_pass }}"
  loop: "{{ awx_iac_organisations }}"


- name: Add AWX Credentials
  awx.awx.credential:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    organization: "{{ item.organization | default('gepaplexx') }}"
    credential_type: "{{ item.credential_type }}"
    inputs: "{{ item.inputs }}"
    state: present
    validate_certs: false
    controller_host: "{{ awx_host_ip }}"
    controller_username: "{{ awx_user }}"
    controller_password: "{{ awx_pass }}"
  loop: "{{ awx_iac_credentials }}"

- name: Add AWX Projects
  awx.awx.project:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    organization: "{{ item.organization | default('gepaplexx') }}"
    scm_type: "{{ item.scm_type }}"
    scm_branch: "{{ item.scm_branch }}"
    scm_url: "{{ item.scm_url }}"
    update_project: "{{ item.update_project }}"
    state: present
    validate_certs: false
    controller_host: "{{ awx_host_ip }}"
    controller_username: "{{ awx_user }}"
    controller_password: "{{ awx_pass }}"
  loop: "{{ awx_iac_projects }}"

- name: Add AWX Inventories
  awx.awx.inventory:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    organization: "{{ item.organization | default('gepaplexx') }}"
    state: present
    validate_certs: false
    controller_host: "{{ awx_host_ip }}"
    controller_username: "{{ awx_user }}"
    controller_password: "{{ awx_pass }}"
  loop: "{{ awx_iac_inventories }}"

- name: Add an inventory source
  awx.awx.inventory_source:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    inventory: "{{ item.inventory }}"
    credential: "{{ item.credential }}"
    overwrite: "{{ item.overwrite }}"
    update_on_launch: "{{ item.update_on_lauch }}"
    organization: "{{ item.organization | default('gepaplexx') }}"
    source_vars: "{{ item.source_vars }}"
  loop: "{{ awx_iac_inventorysources }}"

- name: Add AWX Hosts
  awx.awx.host:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    inventory: "{{ item.inventory }}"
    variables: "{{ item.variables }}"
    state: present
    validate_certs: false
    controller_host: "{{ awx_host_ip }}"
    controller_username: "{{ awx_user }}"
    controller_password: "{{ awx_pass }}"
  loop: "{{ awx_iac_hosts }}"

## ALLES WAS NOCH AUF UNSEREM AWX DEPLOYED IST.
...
