---
- name: Add AWX Organization
  awx.awx.organization:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    state: present
    validate_certs: true
    controller_host: "{{ awx_iac_host_ip }}"
    controller_username: "{{ awx_iac_user }}"
    controller_password: "{{ awx_iac_pass }}"
  loop: "{{ awx_iac_organizations }}"
  