---
- name: Add ThirdParty Auth Github
  awx.awx.settings:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    validate_certs: true
    controller_host: "{{ awx_iac_host_ip }}"
    controller_username: "{{ awx_iac_user }}"
    controller_password: "{{ awx_iac_pass }}"
  loop: "{{ awx_iac_github_auth }}"
  no_log: true
