---
- name: Add AWX Workflow Job Template
  awx.awx.workflow_job_template:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    organization: "{{ item.organization | default('gepaplexx') }}"
    extra_vars: "{{ item.extra_vars }}"
    survey_enabled: "{{ item.survey_enabled }}"
    allow_simultaneous: "{{ item.allow_simultaneous }}"
    ask_variables_on_launch: "{{ item.ask_variables_on_launch }}"
    inventory: "{{ item.inventory }}"
    limit: "{{ item.limit }}"
    scm_branch: "{{ item.scm_branch }}"
    ask_inventory_on_launch: "{{ item.ask_inventory_on_launch }}"
    ask_scm_branch_on_launch: "{{ item.ask_scm_branch_on_launch }}"
    ask_limit_on_launch: "{{ item.ask_limit_on_launch }}"
    state: present
    validate_certs: true
    controller_host: "{{ awx_iac_host_ip }}"
    controller_username: "{{ awx_iac_user }}"
    controller_password: "{{ awx_iac_pass }}"
  loop: "{{ awx_iac_workflow_job_templates }}"
  loop_control:
    label: "{{ item.name }}"
