---
- name: Add AWX Workflow Job Template Nodes
  awx.awx.workflow_job_template_node:
    extra_data: "{{ item.extra_data }}"
    inventory: "{{ item.inventory }}"
    scm_branch: "{{ item.scm_branch }}"
    job_tags: "{{ item.job_tags }}"
    skip_tags: "{{ item.skip_tags }}"
    limit: "{{ item.limit }}"
    workflow_job_template: "{{ item.workflow_job_template }}"
    unified_job_template: "{{ item.unified_job_template }}"
    all_parents_must_converge: "{{ item.all_parents_must_converge }}"
    identifier: "{{ item.identifier }}"
    state: present
    validate_certs: true
    controller_host: "{{ awx_iac_host_ip }}"
    controller_username: "{{ awx_iac_user }}"
    controller_password: "{{ awx_iac_pass }}"
  loop: "{{ awx_iac_workflow_job_template_nodes }}"

# Now the nodes exist. The loop variable is the same. We add the success, failure and always nodes.
- name: Add AWX Workflow Job Template Node Connections
  awx.awx.workflow_job_template_node:
    extra_data: "{{ item.extra_data }}"
    inventory: "{{ item.inventory }}"
    scm_branch: "{{ item.scm_branch }}"
    job_tags: "{{ item.job_tags }}"
    skip_tags: "{{ item.skip_tags }}"
    limit: "{{ item.limit }}"
    workflow_job_template: "{{ item.workflow_job_template }}"
    unified_job_template: "{{ item.unified_job_template }}"
    success_nodes: "{{ item.success_nodes }}"
    failure_nodes: "{{ item.failure_nodes }}"
    always_nodes: "{{ item.always_nodes }}"
    all_parents_must_converge: "{{ item.all_parents_must_converge }}"
    identifier: "{{ item.identifier }}"
    state: present
    validate_certs: true
    controller_host: "{{ awx_iac_host_ip }}"
    controller_username: "{{ awx_iac_user }}"
    controller_password: "{{ awx_iac_pass }}"
  loop: "{{ awx_iac_workflow_job_template_nodes }}"
